global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'z87-linux-host'
    static_configs:
      - targets: ['127.0.0.1:9100']

  - job_name: 'rapl-validation-logic'
    static_configs:
      - targets: ['127.0.0.1:8000']

  - job_name: 'nvidia-dcgm'
    static_configs:
      - targets: ['127.0.0.1:9400']
